name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe what you'd like to see.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Security Auditing (OWASP, Cloud, Zero Trust)
        - Code Auditing (Vulnerabilities, Code Smells)
        - Compliance (SOC 2, HIPAA, PCI-DSS, GDPR, etc.)
        - Forensic (Benford, Fraud, AML)
        - Operational (TIMWOOD, DMAIC, Value Stream)
        - IT Systems (COBIT, Change Management, AD)
        - AI/ML Auditing (Fairness, Model Cards)
        - Red Flag Detection
        - Reporting & Output
        - New Audit Domain
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        As an auditor, I need to assess [X] because...
        Currently, I have to manually...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: |
        Add a new tool called `assess_xyz` that:
        - Takes parameters X, Y, Z
        - Returns findings about...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant standards, frameworks, or documentation
      placeholder: |
        - NIST SP 800-53: https://...
        - OWASP Guide: https://...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
